In [11]:
import sys

if 'google.colab' in sys.modules:

    print("Running in Google Colab")

    print(f"Python version: {sys.version}")

else:

    print("Not running in Google Colab")

Not running in Google Colab

# **Importar datos**

In [16]:
from google.colab import drive

drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

In [ ]:
import pandas as pd
# La ruta estándar a la raíz de tu unidad es esta:

path = '/content/drive/MyDrive/Grupo7/kiva_loans.csv'

 

# Cargar el archivo

df = pd.read_csv(path)

 

# Ver las primeras filas

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Grupo7/kiva_loans.csv'

In [ ]:
import pandas as pd

df = pd.read_csv('/content/kiva_loans_42304_rows.csv')

df.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,1175609,525.0,525.0,Personal Medical Expenses,Health,to buy medicines for her son’s treatment at th...,TJ,Tajikistan,Kanibadam,TJS,100.0,2016-10-27 04:54:27+00:00,2016-10-04 07:00:00+00:00,2016-11-05 02:14:03+00:00,14.0,18,#Health and Sanitation,female,monthly,2016-10-27
1,1056732,350.0,350.0,Butcher Shop,Food,to buy a refrigerator for his butcher shop,MX,Mexico,Ecatepec,MXN,294.0,2016-04-19 15:55:26+00:00,2016-03-31 07:00:00+00:00,2016-04-25 20:14:08+00:00,8.0,10,"#Elderly, #First Loan, #Health and Sanitation,...",male,monthly,2016-04-19
2,773348,225.0,225.0,Food,Food,to buy more raw ingredients for making food sn...,PH,Philippines,"Plaridel-Unidos, Plaridel, Misamis Occidental",PHP,126.0,2014-09-23 08:53:49+00:00,2014-09-19 07:00:00+00:00,2014-10-04 14:33:45+00:00,11.0,9,"volunteer_pick, volunteer_like, #Woman Owned Biz",female,irregular,2014-09-23
3,1076908,325.0,325.0,Farming,Agriculture,to purchase sacks of fertilizer,PH,Philippines,"Pagadian City, Zamboanga del Sur",PHP,126.0,2016-05-27 08:40:46+00:00,2016-05-10 07:00:00+00:00,2016-06-02 12:04:03+00:00,7.0,7,user_favorite,female,irregular,2016-05-27
4,680170,500.0,500.0,Poultry,Agriculture,To purchase more broiler chicks,ZW,Zimbabwe,Nyanga,USD,305.0,2014-03-06 10:29:22+00:00,2014-03-05 08:00:00+00:00,2014-04-02 01:31:55+00:00,8.0,11,"#Woman Owned Biz, #Parent, #Low-profit FP",female,irregular,2014-03-06

In [ ]:
df.shape

df.dtypes

df.info()

df.describe(include='all')

NameError: name 'df' is not defined

In [ ]:
#Duplicados
df.duplicated().sum()
#Valores Nulos
df.isnull().sum().sort_values(ascending=False)
df['loan_amount'].describe()

count    671205.000000
mean        842.397107
std        1198.660073
min          25.000000
25%         275.000000
50%         500.000000
75%        1000.000000
max      100000.000000
Name: loan_amount, dtype: float64

# **Limpieza de datos**

In [ ]:
#Fechas
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['funded_time'] = pd.to_datetime(df['funded_time'], errors='coerce')
#Eliminar duplicados
df = df.drop_duplicates()
#Valores en blanco
# Eliminar filas sin información
df = df.dropna(subset=['loan_amount', 'country'])
# Rellenar valores en blanco
df['sector'] = df['sector'].fillna('Sin datos')